//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Holoville_HOTween_Core_ABSTweenComponentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(System.Object));
		L.RegFunction("Kill", Kill);
		L.RegFunction("Play", Play);
		L.RegFunction("PlayForward", PlayForward);
		L.RegFunction("PlayBackwards", PlayBackwards);
		L.RegFunction("Pause", Pause);
		L.RegFunction("Rewind", Rewind);
		L.RegFunction("Restart", Restart);
		L.RegFunction("Reverse", Reverse);
		L.RegFunction("Complete", Complete);
		L.RegFunction("GoTo", GoTo);
		L.RegFunction("GoToAndPlay", GoToAndPlay);
		L.RegFunction("WaitForCompletion", WaitForCompletion);
		L.RegFunction("WaitForRewind", WaitForRewind);
		L.RegFunction("ApplyCallback", ApplyCallback);
		L.RegFunction("IsTweening", IsTweening);
		L.RegFunction("IsLinkedTo", IsLinkedTo);
		L.RegFunction("GetTweenTargets", GetTweenTargets);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("id", get_id, set_id);
		L.RegVar("intId", get_intId, set_intId);
		L.RegVar("autoKillOnComplete", get_autoKillOnComplete, set_autoKillOnComplete);
		L.RegVar("enabled", get_enabled, set_enabled);
		L.RegVar("timeScale", get_timeScale, set_timeScale);
		L.RegVar("loops", get_loops, set_loops);
		L.RegVar("loopType", get_loopType, set_loopType);
		L.RegVar("position", get_position, set_position);
		L.RegVar("duration", get_duration, null);
		L.RegVar("fullDuration", get_fullDuration, null);
		L.RegVar("elapsed", get_elapsed, null);
		L.RegVar("fullElapsed", get_fullElapsed, null);
		L.RegVar("updateType", get_updateType, null);
		L.RegVar("completedLoops", get_completedLoops, null);
		L.RegVar("destroyed", get_destroyed, null);
		L.RegVar("isEmpty", get_isEmpty, null);
		L.RegVar("isReversed", get_isReversed, null);
		L.RegVar("isLoopingBack", get_isLoopingBack, null);
		L.RegVar("isPaused", get_isPaused, null);
		L.RegVar("hasStarted", get_hasStarted, null);
		L.RegVar("isComplete", get_isComplete, null);
		L.RegVar("isSequenced", get_isSequenced, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Kill(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.Kill();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Play(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.Play();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayForward(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.PlayForward();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayBackwards(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.PlayBackwards();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Pause(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.Pause();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Rewind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.Rewind();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Restart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.Restart();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reverse(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.Reverse(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Complete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			obj.Complete();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GoTo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(float)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				float arg0 = (float)LuaDLL.lua_tonumber(L, 2);
				bool o = obj.GoTo(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(float), typeof(bool)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				float arg0 = (float)LuaDLL.lua_tonumber(L, 2);
				bool arg1 = LuaDLL.lua_toboolean(L, 3);
				bool o = obj.GoTo(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Holoville.HOTween.Core.ABSTweenComponent.GoTo");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GoToAndPlay(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(float)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				float arg0 = (float)LuaDLL.lua_tonumber(L, 2);
				bool o = obj.GoToAndPlay(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(float), typeof(bool)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				float arg0 = (float)LuaDLL.lua_tonumber(L, 2);
				bool arg1 = LuaDLL.lua_toboolean(L, 3);
				bool o = obj.GoToAndPlay(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Holoville.HOTween.Core.ABSTweenComponent.GoToAndPlay");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WaitForCompletion(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			System.Collections.IEnumerator o = obj.WaitForCompletion();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WaitForRewind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			System.Collections.IEnumerator o = obj.WaitForRewind();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ApplyCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(Holoville.HOTween.CallbackType), typeof(Holoville.HOTween.Core.TweenDelegate.TweenCallback)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				Holoville.HOTween.CallbackType arg0 = (Holoville.HOTween.CallbackType)ToLua.ToObject(L, 2);
				Holoville.HOTween.Core.TweenDelegate.TweenCallback arg1 = null;
				LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

				if (funcType3 != LuaTypes.LUA_TFUNCTION)
				{
					 arg1 = (Holoville.HOTween.Core.TweenDelegate.TweenCallback)ToLua.ToObject(L, 3);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 3);
					arg1 = DelegateFactory.CreateDelegate(typeof(Holoville.HOTween.Core.TweenDelegate.TweenCallback), func) as Holoville.HOTween.Core.TweenDelegate.TweenCallback;
				}

				obj.ApplyCallback(arg0, arg1);
				return 0;
			}
			else if (count == 6 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(Holoville.HOTween.CallbackType), typeof(UnityEngine.GameObject), typeof(string), typeof(object), typeof(UnityEngine.SendMessageOptions)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				Holoville.HOTween.CallbackType arg0 = (Holoville.HOTween.CallbackType)ToLua.ToObject(L, 2);
				UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.ToObject(L, 3);
				string arg2 = ToLua.ToString(L, 4);
				object arg3 = ToLua.ToVarObject(L, 5);
				UnityEngine.SendMessageOptions arg4 = (UnityEngine.SendMessageOptions)ToLua.ToObject(L, 6);
				obj.ApplyCallback(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else if (TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(Holoville.HOTween.CallbackType), typeof(Holoville.HOTween.Core.TweenDelegate.TweenCallbackWParms)) && TypeChecker.CheckParamsType(L, typeof(object), 4, count - 3))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				Holoville.HOTween.CallbackType arg0 = (Holoville.HOTween.CallbackType)ToLua.ToObject(L, 2);
				Holoville.HOTween.Core.TweenDelegate.TweenCallbackWParms arg1 = null;
				LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

				if (funcType3 != LuaTypes.LUA_TFUNCTION)
				{
					 arg1 = (Holoville.HOTween.Core.TweenDelegate.TweenCallbackWParms)ToLua.ToObject(L, 3);
				}
				else
				{
					LuaFunction func = ToLua.ToLuaFunction(L, 3);
					arg1 = DelegateFactory.CreateDelegate(typeof(Holoville.HOTween.Core.TweenDelegate.TweenCallbackWParms), func) as Holoville.HOTween.Core.TweenDelegate.TweenCallbackWParms;
				}

				object[] arg2 = ToLua.ToParamsObject(L, 4, count - 3);
				obj.ApplyCallback(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Holoville.HOTween.Core.ABSTweenComponent.ApplyCallback");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsTweening(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(string)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				bool o = obj.IsTweening(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(int)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				bool o = obj.IsTweening(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent), typeof(object)))
			{
				Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.ToObject(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				bool o = obj.IsTweening(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Holoville.HOTween.Core.ABSTweenComponent.IsTweening");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsLinkedTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			object arg0 = ToLua.ToVarObject(L, 2);
			bool o = obj.IsLinkedTo(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTweenTargets(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)ToLua.CheckObject(L, 1, typeof(Holoville.HOTween.Core.ABSTweenComponent));
			System.Collections.Generic.List<object> o = obj.GetTweenTargets();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_id(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			string ret = obj.id;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index id on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_intId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			int ret = obj.intId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index intId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_autoKillOnComplete(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.autoKillOnComplete;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index autoKillOnComplete on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_enabled(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.enabled;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index enabled on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_timeScale(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float ret = obj.timeScale;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index timeScale on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_loops(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			int ret = obj.loops;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index loops on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_loopType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			Holoville.HOTween.LoopType ret = obj.loopType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index loopType on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_position(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float ret = obj.position;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index position on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_duration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float ret = obj.duration;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index duration on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_fullDuration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float ret = obj.fullDuration;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index fullDuration on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_elapsed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float ret = obj.elapsed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index elapsed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_fullElapsed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float ret = obj.fullElapsed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index fullElapsed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_updateType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			Holoville.HOTween.UpdateType ret = obj.updateType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index updateType on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_completedLoops(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			int ret = obj.completedLoops;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index completedLoops on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_destroyed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.destroyed;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index destroyed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isEmpty(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.isEmpty;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isEmpty on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isReversed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.isReversed;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isReversed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isLoopingBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.isLoopingBack;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isLoopingBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isPaused(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.isPaused;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isPaused on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasStarted(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.hasStarted;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index hasStarted on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isComplete(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.isComplete;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isComplete on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isSequenced(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool ret = obj.isSequenced;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isSequenced on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_id(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.id = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index id on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_intId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.intId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index intId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_autoKillOnComplete(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.autoKillOnComplete = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index autoKillOnComplete on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_enabled(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.enabled = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index enabled on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_timeScale(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.timeScale = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index timeScale on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_loops(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.loops = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index loops on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_loopType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			Holoville.HOTween.LoopType arg0 = (Holoville.HOTween.LoopType)ToLua.CheckObject(L, 2, typeof(Holoville.HOTween.LoopType));
			obj.loopType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index loopType on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_position(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Holoville.HOTween.Core.ABSTweenComponent obj = (Holoville.HOTween.Core.ABSTweenComponent)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.position = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index position on a nil value" : e.Message);
		}
	}
}

