//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Holoville_HOTween_Plugins_Core_ABSTweenPluginWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Holoville.HOTween.Plugins.Core.ABSTweenPlugin), typeof(System.Object));
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}
}

