//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PrefabBinderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PrefabBinder), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetObj", GetObj);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("items", get_items, set_items);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObj(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PrefabBinder obj = (PrefabBinder)ToLua.CheckObject(L, 1, typeof(PrefabBinder));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Object o = obj.GetObj(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_items(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PrefabBinder obj = (PrefabBinder)o;
			PrefabBinder.Item[] ret = obj.items;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index items on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_items(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PrefabBinder obj = (PrefabBinder)o;
			PrefabBinder.Item[] arg0 = ToLua.CheckObjectArray<PrefabBinder.Item>(L, 2);
			obj.items = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index items on a nil value" : e.Message);
		}
	}
}

