///This code was generated by menu [Tools/sproto2cs], DO NOT EDIT!

public class c2s {
 public const string sproto = @"
.package {
	type 0 : integer
	session 1 : integer
}


sayhello 1 {
	request {
	  what 0 : string
	}
	response {
	  error_code 0 : integer
	  msg 1 : string
	}
}
";
}